name: Build Docker Image
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        description: Whether to deploy the build images
jobs:
  deletion:
    needs: build
    if:  "github.ref == 'refs/heads/master' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.deploy))"
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Packages
        uses: SmartsquareGmbH/delete-old-packages@v0.8.1
        with:
            user: therobot2105
            type: container
            keep: 4 
            names: |
                texlive-small
                texlive-full
            dry-run: false
  build:
    if: "!(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]'))"
    strategy:
      matrix:
        scheme: [small, full]
    name: Build TeXLive [${{ matrix.scheme }}-scheme]
    runs-on: ubuntu-latest
    env:
      SCHEME: ${{ matrix.scheme }}
      TAG: ghcr.io/therobot2105/texlive-${{ matrix.scheme }}
    steps:
      - name: Get version
        run: |
          echo "VERSION=$(date "+%Y%m%d")"  >> "$GITHUB_ENV"
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          build-args: scheme=${{ env.SCHEME }}
          tags: texlive-${{ env.SCHEME }}
          load: true
      - name: Test pdflatex
        run: |
          docker run --rm texlive-$SCHEME pdflatex --version
          cat <<EOF >ref.bib
          @book{knuth1997,
            author    = {Donald E. Knuth},
            title     = {The Art of Computer Programming},
            volume    = {1},
            publisher = {Addison-Wesley},
            year      = {1997}
          }
          EOF
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \usepackage[style=authoryear]{biblatex}
          \addbibresource{ref.bib}
          \begin{document}
          Test~\cite{knuth1997}.

          \printbibliography
          \end{document}
          EOF
          docker run --rm -v "$(pwd):/data" -w /data texlive-$SCHEME \
            python3 /opt/texlive/bin/texliveonfly \
            -c latexmk -a "-g -pdf -halt-on-error -interaction=nonstopmode" test.tex
          file test.pdf | grep -q ' PDF '
      - name: Test latexindent
        run: |
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{newtxtext}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data texlive-$SCHEME latexindent test.tex
        if: "matrix.scheme == 'full'"
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: "github.ref == 'refs/heads/master' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.deploy))"
      - name: Deploy
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.alpine
          build-args: scheme=${{ env.SCHEME }}
          tags: ${{ env.TAG }}:${{ env.VERSION }},${{ env.TAG }}:latest
          push: true
        if: "github.ref == 'refs/heads/master' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.deploy))"
