name: Delete old Packages
on:
    workflow_dispatch:

jobs:
    deletion:
      runs-on: ubuntu-latest
      steps:
        - name: Delete old Packages
          uses: SmartsquareGmbH/delete-old-packages@v0.8.1
          with:
              user: therobot2105
              type: container
              keep: 0
              names: |
                  texlive-small
                  texlive-full
              dry-run: true